#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jul 27 11:36:10 2018

@author: Benson
"""


# list
a = [0.1, 0.5, 0.25, 0.8, 0.9]
for i in a:        # i 為每個元素
    print( i*100 )    
    
	
# tuple
a = (0.1, 0.5, 0.25, 0.8, 0.9)
for i in a:        # i 為每個元素
    print( i*100 )
    

# string
a = "ABCDEFG"
for i in a:        # i 為每個字母
    print( i )
    

# dictionary
a = { "id": "1", "name": "benson" }
for i in a:
    print( i )      # i 為鍵(key)，a[i] 為值
    print( a[i] )

	

# Common use of for loop in data processing
a = [0.1, 0.5, 0.25, 0.8, 0.9]            # 待轉換成百分比的數值
percent = []                        # 定義空 list
for i in a:   # 把 a 內的數值逐一乘上100，然後儲存到 percent
    percent.append( i * 100 )
	
	

# for loop example
for i in range(5):
    print( i )
    
	
	
# check the sequence generated by range()       
list( range(5) )
list( range(0, 5, 2) )       



# break
for i in range(5):
    if i == 2:
        break
    print( i )


# continue
for i in range(5):
    if i == 2:
        continue
    print( i )




# enumerate()，同時在for loop 裡獲得元數的index以及內容。
for i, j in enumerate(["a","b","c"]):
    print( i )
    print( j )

	
	
# another way that equavalent to enumerate()
a = ["a","b","c"]
for i in range(0, len(a)):
    print( i )
    print( j )
	
	
	
	
# list of tuples
a = [ (0, "a"), (1, "b"), (2, "c") ]
for i in a:    
    print( i )      # for 用於 list of tuples 時， i 會等於每個 Tuple
    
	
	
	
# list of tuples - getting elements inside tuple
a = [ (0, "a"), (1, "b"), (2, "c") ]
for i in a:    
    print( i[0] )      
    print( i[1] )     
	# i[0] 會等於 0, 1, 2，型別是整數，i[1] 會等於 "a", "b", "c"，型別是字串。
	# 但由於整數無法和字串直接相加，因此我們要用 str() 函數把 i[0] 轉換為字串，
	# 才能夠把 i[0] 、 ", " 、 i[1] 三個資料相加打印出屏幕。


	
	
# list of tuples - 2 variables
a = [ (0, "a"), (1, "b"), (2, "c") ]
for i, j in a:        # 原來我們可以用兩個變數儲存 Tuple 內每個元素！
    print( i )
    print( j )   
    #for 用於 list of tuples 時， i, j 會順序等於 Tuple 內每個元素

	
	
# list of tuples - 3 variables
a = [ (0, "a", "a1"), (1, "b", "b1"), (2, "c", "c1") ]
for i, j, k in a:        # 用三個變數儲存 Tuple 內每個元素
    print( i )
    print( j )   
    print( k )    
    # for 用於 list of tuples 時， i, j, k 會順序等於 Tuple 內每個元素



    

# exercise

    
    
    
    
    